version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

  service1:
    build: ./service_1
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  service2:
    build: ./service_2
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]  # adjust for each service
      interval: 10s
      timeout: 3s
      retries: 3
